# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('birth_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('payment', models.IntegerField()),
                ('currently_emp', models.BooleanField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='TutorialModel',
        ),
    ]
